config/routes.rb
Rails.application.routes.draw do
  root 'test_takers#index'
  resources :test_takers do
    collection do
      post 'bulk_insert', format: [:json, :csv]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test_taker.rb
class TestTaker < ApplicationRecord

  validates_presence_of :login, :password, :title, :firstname, :lastname, :address, :email, :gender, :picture
  validates_uniqueness_of :login

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/test_takers_controller.rb
class TestTakersController < ApplicationController
  before_action :set_test_taker, only: [:show, :edit, :update, :destroy]
  wrap_parameters :test_taker,include: [:data]


  # GET /test_takers
  # GET /test_takers.json
  def index
    @test_takers = TestTaker.all.page(params[:page]).per(10)
  end

  def bulk_insert
    file = FileService.new(params[:file])

    redirect_to test_takers_path, notice: 'file type not supported' and return unless file.supported_type?
    params[:test_taker]= { data: file.data_array}
    result = TestTaker.create(test_taker_params[:data])
    @notice = result.select{|e| !e.errors.empty? }.map { |e|
      {
          login: e.login,
          message: e.errors.full_messages.join(',')
      }
    }
    @notice = 'Successfully inserted' if @notice.empty?
    redirect_to test_takers_path, notice: @notice

  end

  # GET /test_takers/1
  # GET /test_takers/1.json
  def show
  end

  # GET /test_takers/new
  def new
    @test_taker = TestTaker.new
  end

  # GET /test_takers/1/edit
  def edit
  end

  # POST /test_takers
  # POST /test_takers.json
  def create
    @test_taker = TestTaker.new(test_taker_params)

    respond_to do |format|
      if @test_taker.save
        format.html { redirect_to @test_taker, notice: 'Test taker was successfully created.' }
        format.json { render :show, status: :created, location: @test_taker }
      else
        format.html { render :new }
        format.json { render json: @test_taker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_takers/1
  # PATCH/PUT /test_takers/1.json
  def update
    respond_to do |format|
      if @test_taker.update(test_taker_params)
        format.html { redirect_to @test_taker, notice: 'Test taker was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_taker }
      else
        format.html { render :edit }
        format.json { render json: @test_taker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_takers/1
  # DELETE /test_takers/1.json
  def destroy
    @test_taker.destroy
    respond_to do |format|
      format.html { redirect_to test_takers_url, notice: 'Test taker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_taker
      @test_taker = TestTaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_taker_params
      params.require(:test_taker  ).permit(data: [:login, :password, :title, :lastname, :firstname, :gender, :email, :picture, :address])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_takers_helper.rb
module TestTakersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTakers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/test_takers/_form.html.erb
<%= form_with(model: test_taker, local: true) do |form| %>
  <% if test_taker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_taker.errors.count, "error") %> prohibited this test_taker from being saved:</h2>

      <ul>
      <% test_taker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_takers/edit.html.erb
<h1>Editing Test Taker</h1>

<%= render 'form', test_taker: @test_taker %>

<%= link_to 'Show', @test_taker %> |
<%= link_to 'Back', test_takers_path %>

app/views/test_takers/index.html.erb
<div class="container">

  <h1> Welcome to Test Takers list</h1>
  <p id="notice"><%= notice %></p>
  <div class="row right-align">
    <%= form_tag  bulk_insert_test_takers_path, multipart: true do %>
        <%= file_field_tag :file ,required: true, class: ' col m3'%>
        <%= submit_tag "Import Users", class: 'btn blue col m2' %>
    <% end %>
  </div>


  <table class="striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>Login</th>
      <!--<th>Password</th>-->
      <th>Title</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Gender</th>
      <th>Email</th>
      <!--<th>Picture</th>-->
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @test_takers.each do |test_taker| %>
        <tr>
          <td><%= test_taker.id %></td>
          <td>
            <%= image_tag(test_taker.picture) %>
            <%= test_taker.login %></td>
          <!--<td><%= test_taker.password %></td>-->
          <td><%= test_taker.title %></td>
          <td><%= test_taker.lastname %></td>
          <td><%= test_taker.firstname %></td>
          <td><%= test_taker.gender %></td>
          <td><%= test_taker.email %></td>
          <!--<td><%= test_taker.picture %></td>-->
          <td><%= test_taker.address %></td>
        </tr>
    <% end %>
    </tbody>
  </table>


  <div class="right-align">
     <%= paginate @test_takers %>
  </div>
</div>



<!--<%= link_to 'New Test Taker', new_test_taker_path, class: 'btn' %>-->

app/views/test_takers/new.html.erb
<h1>New Test Taker</h1>

<%= render 'form', test_taker: @test_taker %>

<%= link_to 'Back', test_takers_path %>

app/views/test_takers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @test_taker.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @test_taker.password %>
</p>

<p>
  <strong>Title:</strong>
  <%= @test_taker.title %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @test_taker.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @test_taker.firstname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @test_taker.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @test_taker.email %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @test_taker.picture %>
</p>

<p>
  <strong>Address:</strong>
  <%= @test_taker.address %>
</p>

<%= link_to 'Edit', edit_test_taker_path(@test_taker) %> |
<%= link_to 'Back', test_takers_path %>